name: Deploy

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16
  FILES_PATH: /var/www/vhosts/bp/
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
        name: Collect dependencies
      - run: yarn run eslint ./src/
        name: Check formatting
      - run: yarn test --clearCache
        name: Clear test cache
      - name: Run tests
        run: yarn test
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            node_modules

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            node_modules
      - run: CI=false yarn build
        name: Build static page
      - name: Store build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Clean workspace
        run: rm -rf *
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
      - run: rm -rf ${{ env.FILES_PATH }}*
        name: Delete old files
      - run: cp -r * ${{ env.FILES_PATH }}
        name: Copy new files
