name: Test

on:
  push:
    branches:
      - '**'
      - '!main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 16
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
        name: Collect dependencies
      - run: yarn run eslint ./src/
        name: Check formatting
      - run: yarn test --clearCache
        name: Clear test cache
      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
      - run: CI=false yarn build
        name: Build static page
