name: Test

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
      - '!main'

env:
  NODE_VERSION: 16
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
        name: Collect dependencies
      - run: eslint ./src/
        name: Check formatting
      - run: yarn test --clearCache
        name: Clear test cache
      - name: Run tests
        run: yarn test
